-- https://school.programmers.co.kr/learn/courses/30/lessons/59041
SELECT NAME as 이름, COUNT(NAME) as 횟수
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
GROUP BY NAME
HAVING COUNT(NAME) >=2
ORDER BY NAME


-- https://school.programmers.co.kr/learn/courses/30/lessons/131536
SELECT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
GROUP BY USER_ID, PRODUCT_ID --조합이 같은 것 끼리 그룹화함.
HAVING COUNT(*) > 1
ORDER BY USER_ID ASC, PRODUCT_ID DESC

# 다른 풀이 방법,, sub query,, 
SELECT DISTINCT USER_ID, PRODUCT_ID
FROM ONLINE_SALE
WHERE (USER_ID, PRODUCT_ID) IN (
    SELECT USER_ID, PRODUCT_ID
    FROM ONLINE_SALE
    GROUP BY USER_ID, PRODUCT_ID
    HAVING COUNT(*) > 1
)
ORDER BY USER_ID ASC, PRODUCT_ID DESC;